apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1    
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: prashantsiddhpura/expensetracker-backend:latest
        envFrom:
        - configMapRef: 
            name: backend-configmap
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi  