services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: exp-frontend
    restart: always
    depends_on:
      - backend
    networks:
      - appnet


  backend:
    build:
      context: ./backend
    container_name: exp-backend
    restart: always
    depends_on:
      - mysql
    networks:
      - appnet
    ports:
      - "5000:5000"
    environment:
      - "./backend/.env"


  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense_tracker
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pprashant@383"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - appnet


networks:
  appnet:

volumes:
  db-data: