apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv2
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain   
  storageClassName: local-storage  
  hostPath:
    path: /mnt/data2