apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc2
  namespace: dev
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
