apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: mysql-vpa
  namespace: dev
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mysql-deployment
  updatePolicy:
    updateMode: "Auto"   # Options: Off | Initial | Recreate | Auto
