apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: dev
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1    
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
        
        ports:
          - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-data
          - name: initdb
            mountPath: /docker-entrypoint-initdb.d  
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc2
      - name: initdb
        configMap:
          name: mysql-initdb    